import { randomUUID } from 'node:crypto';
import { BaseStore, type DbMigration, type SqliteDatabase } from '@tkottke90/llm-common-types/db';
import { logger } from '../config/logger.js';
import { isCronTrigger, statusForSavedSchedule, type CronConfig } from './cron-config.js';
import { settleCronRun } from './cron-settlement.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type WorkspaceStatus = 'active' | 'closed' | 'abandoned';

export interface Workspace {
  id: string;
  name: string;
  description: string | null;
  goal: string | null;
  location: string;
  remoteUrl: string | null;
  javascript: boolean;
  python: boolean;
  git: boolean;
  wikiId: string | null;
  systemPrompt: string | null;
  threadId: string | null;
  summaryPath: string | null;
  lastSummarizedMessageId: string | null;
  createdAt: string;
  updatedAt: string;
  lastChange: string;
}

export interface NewWorkspaceInput {
  name: string;
  description?: string | null;
  goal?: string | null;
  location: string;
  remoteUrl?: string | null;
  javascript?: boolean;
  python?: boolean;
  git?: boolean;
  wikiId?: string | null;
  systemPrompt?: string | null;
}

export interface PatchWorkspaceInput {
  name?: string;
  description?: string | null;
  goal?: string | null;
  remoteUrl?: string | null;
  javascript?: boolean;
  python?: boolean;
  git?: boolean;
  wikiId?: string | null;
  systemPrompt?: string | null;
  threadId?: string;
  summaryPath?: string;
  lastSummarizedMessageId?: string;
}

export interface CloseProgress {
  mergeSelections?: { filename: string; targetDomainId: string }[];
  dependencySelections?: { removeNodeModules: boolean; removePythonEnv: boolean };
}

export interface Project {
  id: string;
  workspaceId: string;
  winCondition: string;
  dueAt: string | null;
  status: 'active' | 'closing' | 'closed' | 'abandoned';
  closedAt: string | null;
  closeIntent: 'close' | 'abandon' | null;
  snapshotPath: string | null;
  closeProgress: CloseProgress | null;
}

export interface NewProjectInput extends NewWorkspaceInput {
  /** Shared workspace/project row id, generated by the caller so it can
   * provision resources (e.g. the project wiki domain) before the insert. */
  id: string;
  winCondition: string;
  dueAt?: string | null;
}

export interface PatchProjectInput extends PatchWorkspaceInput {
  winCondition?: string;
  dueAt?: string | null;
  closeProgress?: CloseProgress;
}

// 'scheduled' is the idle state of a task with an enabled cron trigger:
// waiting for its next fire time. The cron registry only fires a task that
// is 'scheduled', so any other status (queued, running, waiting on the user,
// paused) means "busy — skip this fire". See
// docs/superpowers/specs/2026-09-26-cron-task-triggers-design.md §1.
export type TaskStatus =
  | 'pending'
  | 'scheduled'
  | 'ready'
  | 'running'
  | 'waiting_on_user'
  | 'blocked'
  | 'done'
  | 'failed'
  | 'cancelled';

export type TriggerType = 'manual' | 'chat' | 'cron_once' | 'cron_repeat' | 'webhook';

export interface PlanStep {
  step: string;
  done: boolean;
}

export interface Task {
  id: string;
  workspaceId: string | null;
  title: string;
  description: string | null;
  outcome: string | null;
  status: TaskStatus;
  assignedTo: 'user' | 'agent' | null;
  dueAt: string | null;
  expiresAt: string | null;
  triggerType: TriggerType;
  triggerConfig: unknown | null;
  trackerType: string | null;
  trackerId: string | null;
  plan: PlanStep[] | null;
  // Dedicated automated-execution thread for a task with no workspace —
  // minted lazily on the task's own first run (see task-execution.ts).
  // Workspace-scoped tasks reuse workspace.threadId instead.
  threadId: string | null;
  // Carries a HITL answer from the /hitl route's task re-enqueue branch
  // through to the next executeTask() run, which consumes (clears) it and
  // resumes the paused LangGraph checkpoint via Command({ resume }) — a
  // fresh message cannot unblock an interrupt().
  resumeAnswer: string | null;
  // 'agent' rows were spawned by the spawn_sub_agent tool — see
  // docs/superpowers/specs/2026-09-09-sub-agent-tooling-design.md. They're
  // excluded from dequeueNext()/getRunningEntry()'s per-scope accounting and
  // deliver a completion-notification turn into parentThreadId instead of
  // (only) mirroring task_queue's own status.
  origin: 'user' | 'agent';
  // How this *task* was created ('webhook' = POST /api/v1/webhooks/tasks).
  // Deliberately separate from `origin` above, which is load-bearing in the
  // scheduler's dequeue logic (origin='agent' gets dispatch-group/
  // single-flight treatment) — never add a value here to `origin` instead.
  // Also distinct from task_queue's own trigger_source/TriggerSource, which
  // records what started a *run*, not how the task itself was created.
  triggerSource: 'user' | 'webhook';
  parentThreadId: string | null;
  dispatchGroupId: string | null;
  role: string | null;
  // Set when status is 'blocked' because a required dependency (see
  // TaskDependency below) failed or was cancelled — distinct from a plain
  // user-initiated pause, which carries no reason here (see task_queue's own
  // pause_reason instead). Cleared to null on any transition out of 'blocked'.
  blockedReason: 'dependency_failed' | null;
  createdAt: string;
  updatedAt: string;
}

// An edge in the task dependency graph: `taskId` cannot become 'ready' until
// `dependsOnTaskId` satisfies this edge's rule. See isTaskReady()/
// hasBrokenDependency()/releaseEligibleDependents() below for the gating
// logic, and docs/superpowers/specs/2026-09-22-task-dependencies-design.md
// for the full design.
export interface TaskDependency {
  id: number;
  taskId: string;
  dependsOnTaskId: string;
  // true: satisfied only when the target reaches 'done'; 'failed'/'cancelled'
  // permanently breaks this edge. false: satisfied by any terminal state.
  requireSuccess: boolean;
  // true: the target reaching 'blocked' (human-paused) also satisfies this
  // edge, in addition to whatever requireSuccess implies.
  whileBlocked: boolean;
  createdAt: string;
}

// One outgoing dependency edge with enough about its target for display —
// see listDependencyEdgesForTasks().
export interface DependencyEdgeSummary {
  dependency: TaskDependency;
  target: { id: string; title: string; trackerId: string | null; status: TaskStatus };
  satisfied: boolean;
}

// A task's trailing run of failed runs — see failedRunStreaks().
export interface FailedRunStreak {
  attempts: number;
  lastSummary: string | null;
}

export interface NewTaskInput {
  workspaceId?: string | null;
  title: string;
  description?: string | null;
  outcome?: string | null;
  assignedTo?: 'user' | 'agent' | null;
  dueAt?: string | null;
  expiresAt?: string | null;
  triggerType?: TriggerType;
  triggerConfig?: unknown | null;
  trackerType?: string | null;
  trackerId?: string | null;
  plan?: PlanStep[] | null;
  origin?: 'user' | 'agent';
  triggerSource?: 'user' | 'webhook';
  parentThreadId?: string | null;
  dispatchGroupId?: string | null;
  role?: string | null;
}

export interface PatchTaskInput {
  workspaceId?: string | null;
  title?: string;
  description?: string | null;
  outcome?: string | null;
  status?: TaskStatus;
  assignedTo?: 'user' | 'agent' | null;
  dueAt?: string | null;
  expiresAt?: string | null;
  triggerType?: TriggerType;
  triggerConfig?: unknown | null;
  trackerType?: string | null;
  trackerId?: string | null;
  plan?: PlanStep[] | null;
  threadId?: string | null;
  resumeAnswer?: string | null;
  blockedReason?: 'dependency_failed' | null;
}

// What started one run (task_queue row) of a task — drives run labels and,
// for the cron trigger, which runs count toward its iteration budget.
export type TriggerSource = 'manual' | 'webhook' | 'schedule' | 'catch_up' | 'chat' | 'agent';

export interface TaskQueueEntry {
  id: string;
  taskId: string;
  status: 'pending' | 'running' | 'paused' | 'done' | 'failed' | 'cancelled';
  position: number;
  enqueuedAt: string;
  startedAt: string | null;
  finishedAt: string | null;
  recoveryAttempts: number;
  pauseReason: 'chat' | 'user' | null;
  pausedAt: string | null;
  // Each queue row is one run of its task, with its own 'task'-type thread
  // (minted on the run's first start, reused on resume) and a persisted
  // one-line summary once it settles — see
  // docs/superpowers/specs/2026-09-26-cron-task-triggers-design.md §1.
  threadId: string | null;
  summary: string | null;
  triggerSource: TriggerSource;
  scheduledFor: string | null;
}

// One run of a task as the run-history surfaces see it (drawer, kickoff
// message, read_task_run) — a TaskQueueEntry plus its 1-based position
// among all of that task's runs.
export interface TaskRun extends TaskQueueEntry {
  runNumber: number;
}

export interface EnqueueOptions {
  triggerSource?: TriggerSource;
  scheduledFor?: string | null;
}

export interface TaskListFilters {
  workspaceId?: string | null;
  status?: TaskStatus;
}

// ---------------------------------------------------------------------------
// Raw DB row interfaces
// ---------------------------------------------------------------------------

interface RawWorkspaceRow {
  id: string;
  name: string;
  description: string | null;
  goal: string | null;
  location: string;
  remote_url: string | null;
  javascript: number;
  python: number;
  git: number;
  wiki_id: string | null;
  system_prompt: string | null;
  thread_id: string | null;
  summary_path: string | null;
  last_summarized_message_id: string | null;
  created_at: string;
  updated_at: string;
  last_change: string;
}

interface RawProjectRow {
  id: string;
  workspace_id: string;
  win_condition: string;
  due_at: string | null;
  status: 'active' | 'closing' | 'closed' | 'abandoned';
  closed_at: string | null;
  close_intent: 'close' | 'abandon' | null;
  snapshot_path: string | null;
  close_progress: string | null;
}

interface RawTaskRow {
  id: string;
  workspace_id: string | null;
  title: string;
  description: string | null;
  outcome: string | null;
  status: TaskStatus;
  assigned_to: 'user' | 'agent' | null;
  due_at: string | null;
  expires_at: string | null;
  trigger_type: TriggerType;
  trigger_config: string | null;
  tracker_type: string | null;
  tracker_id: string | null;
  plan: string | null;
  thread_id: string | null;
  resume_answer: string | null;
  origin: 'user' | 'agent';
  trigger_source: 'user' | 'webhook';
  parent_thread_id: string | null;
  dispatch_group_id: string | null;
  role: string | null;
  blocked_reason: 'dependency_failed' | null;
  created_at: string;
  updated_at: string;
}

interface RawTaskDependencyRow {
  id: number;
  task_id: string;
  depends_on_task_id: string;
  require_success: number;
  while_blocked: number;
  created_at: string;
}

interface RawQueueRow {
  id: string;
  task_id: string;
  status: 'pending' | 'running' | 'paused' | 'done' | 'failed' | 'cancelled';
  position: number;
  enqueued_at: string;
  started_at: string | null;
  finished_at: string | null;
  recovery_attempts: number;
  pause_reason: 'chat' | 'user' | null;
  paused_at: string | null;
  thread_id: string | null;
  summary: string | null;
  trigger_source: TriggerSource;
  scheduled_for: string | null;
}

// ---------------------------------------------------------------------------
// Row <-> record mapping
// ---------------------------------------------------------------------------

function mapWorkspace(row: RawWorkspaceRow): Workspace {
  return {
    id: row.id,
    name: row.name,
    description: row.description,
    goal: row.goal,
    location: row.location,
    remoteUrl: row.remote_url,
    javascript: row.javascript === 1,
    python: row.python === 1,
    git: row.git === 1,
    wikiId: row.wiki_id,
    systemPrompt: row.system_prompt,
    threadId: row.thread_id,
    summaryPath: row.summary_path,
    lastSummarizedMessageId: row.last_summarized_message_id,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    lastChange: row.last_change,
  };
}

function mapProject(row: RawProjectRow): Project {
  return {
    id: row.id,
    workspaceId: row.workspace_id,
    winCondition: row.win_condition,
    dueAt: row.due_at,
    status: row.status,
    closedAt: row.closed_at,
    closeIntent: row.close_intent,
    snapshotPath: row.snapshot_path,
    closeProgress: row.close_progress ? (JSON.parse(row.close_progress) as CloseProgress) : null,
  };
}

function mapTask(row: RawTaskRow): Task {
  return {
    id: row.id,
    workspaceId: row.workspace_id,
    title: row.title,
    description: row.description,
    outcome: row.outcome,
    status: row.status,
    assignedTo: row.assigned_to,
    dueAt: row.due_at,
    expiresAt: row.expires_at,
    triggerType: row.trigger_type,
    triggerConfig: row.trigger_config ? (JSON.parse(row.trigger_config) as unknown) : null,
    trackerType: row.tracker_type,
    trackerId: row.tracker_id,
    plan: row.plan ? (JSON.parse(row.plan) as PlanStep[]) : null,
    threadId: row.thread_id,
    resumeAnswer: row.resume_answer,
    origin: row.origin,
    triggerSource: row.trigger_source,
    parentThreadId: row.parent_thread_id,
    dispatchGroupId: row.dispatch_group_id,
    role: row.role,
    blockedReason: row.blocked_reason,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

function mapTaskDependency(row: RawTaskDependencyRow): TaskDependency {
  return {
    id: row.id,
    taskId: row.task_id,
    dependsOnTaskId: row.depends_on_task_id,
    requireSuccess: row.require_success === 1,
    whileBlocked: row.while_blocked === 1,
    createdAt: row.created_at,
  };
}

function mapQueueEntry(row: RawQueueRow): TaskQueueEntry {
  return {
    id: row.id,
    taskId: row.task_id,
    status: row.status,
    position: row.position,
    enqueuedAt: row.enqueued_at,
    startedAt: row.started_at,
    finishedAt: row.finished_at,
    recoveryAttempts: row.recovery_attempts,
    pauseReason: row.pause_reason,
    pausedAt: row.paused_at,
    threadId: row.thread_id,
    summary: row.summary,
    triggerSource: row.trigger_source,
    scheduledFor: row.scheduled_for,
  };
}

// ---------------------------------------------------------------------------
// DDL migrations
// ---------------------------------------------------------------------------

// Version numbers must be unique across ALL stores sharing this database.
// 1=observability, 2=cost-store, 3=evaluations, 4=threads, 5=observability,
// 6=evaluations (judge_calibrations), 7=observability, 8=evaluations,
// 9=(free), 10-12=threads (type column), 13-16=threads (provider/model columns),
// 17=shell_audit_log. Versions 18-22 are claimed by WorkspaceStore here.
// 23=WorkspaceStore (workspaces.thread_id/summary_path/last_summarized_message_id,
// for the Workspace Chat Tab feature). 24=WorkspaceStore (tasks.thread_id/
// resume_answer, for Automated Task Execution). 25=WorkspaceStore
// (projects.close_intent/snapshot_path/close_progress, for the Project Close
// Process feature). 26=WorkspaceStore (task_queue.pause_reason/paused_at,
// for Task Cancel/Pause/Take-over). 27=WorkspaceStore (tasks.origin/
// parent_thread_id/dispatch_group_id/role, for sub-agent tooling).
// 28=ToolSettingsStore (tool_settings/thread_tools tables, tool-settings-store.ts).
// 29=threads (tools_customized_at column). 28-29 are for Per-Thread/Global
// Tool Management — issue #171 — see thread-store.ts's own comment.
// 30=ToolSettingsStore (drops tool_settings.enabled/default_include —
// moved to config.yaml, for the 2026-09-13 tool settings redesign).
// 31=WorkspaceStore (task_dependencies table, tasks.blocked_reason column,
// for the task-dependency-gating feature — see
// docs/superpowers/specs/2026-09-22-task-dependencies-design.md).
// 32=WorkspaceStore (task_queue.thread_id/summary/trigger_source/
// scheduled_for — one thread + persisted summary per run, for the cron
// task triggers feature — see
// docs/superpowers/specs/2026-09-26-cron-task-triggers-design.md).
const MIGRATIONS: DbMigration[] = [
  {
    version: 18,
    sql: `
      CREATE TABLE IF NOT EXISTS workspaces (
        id            TEXT PRIMARY KEY,
        name          TEXT NOT NULL,
        description   TEXT,
        goal          TEXT,
        location      TEXT NOT NULL,
        remote_url    TEXT,
        javascript    INTEGER NOT NULL DEFAULT 0,
        python        INTEGER NOT NULL DEFAULT 0,
        git           INTEGER NOT NULL DEFAULT 0,
        wiki_id       TEXT,
        system_prompt TEXT,
        created_at    TEXT NOT NULL,
        updated_at    TEXT NOT NULL,
        last_change   TEXT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_workspaces_updated ON workspaces(updated_at);
    `,
  },
  {
    version: 19,
    sql: `
      CREATE TABLE IF NOT EXISTS projects (
        id            TEXT PRIMARY KEY,
        workspace_id  TEXT NOT NULL UNIQUE REFERENCES workspaces(id),
        win_condition TEXT NOT NULL,
        due_at        TEXT,
        status        TEXT NOT NULL DEFAULT 'active',
        closed_at     TEXT
      );
    `,
  },
  {
    version: 20,
    sql: `
      CREATE TABLE IF NOT EXISTS tasks (
        id             TEXT PRIMARY KEY,
        workspace_id   TEXT REFERENCES workspaces(id),
        title          TEXT NOT NULL,
        description    TEXT,
        outcome        TEXT,
        status         TEXT NOT NULL DEFAULT 'pending',
        assigned_to    TEXT,
        due_at         TEXT,
        expires_at     TEXT,
        trigger_type   TEXT NOT NULL DEFAULT 'manual',
        trigger_config TEXT,
        tracker_type   TEXT,
        tracker_id     TEXT,
        plan           TEXT,
        created_at     TEXT NOT NULL,
        updated_at     TEXT NOT NULL
      );
      CREATE INDEX IF NOT EXISTS idx_tasks_workspace ON tasks(workspace_id);
      CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status);
    `,
  },
  {
    version: 21,
    sql: `
      CREATE TABLE IF NOT EXISTS task_queue (
        id           TEXT PRIMARY KEY,
        task_id      TEXT NOT NULL REFERENCES tasks(id),
        status       TEXT NOT NULL DEFAULT 'pending',
        position     INTEGER NOT NULL,
        enqueued_at  TEXT NOT NULL,
        started_at   TEXT,
        finished_at  TEXT
      );
      CREATE INDEX IF NOT EXISTS idx_task_queue_status_position ON task_queue(status, position);
    `,
  },
  {
    version: 22,
    sql: `ALTER TABLE task_queue ADD COLUMN recovery_attempts INTEGER NOT NULL DEFAULT 0;`,
  },
  {
    version: 23,
    // No REFERENCES threads(id) here (unlike task_queue.task_id above) —
    // SQLite requires ALTER TABLE ADD COLUMN's referenced table to already
    // exist at ALTER time (a plain CREATE TABLE can forward-reference one
    // that doesn't exist yet, but ADD COLUMN can't), and WorkspaceStore is
    // frequently constructed standalone, on a db with no threads table at
    // all (e.g. every WorkspaceStore-only test). thread_id is still a plain
    // threads.id value; it just isn't DB-enforced as a foreign key.
    sql: `
      ALTER TABLE workspaces ADD COLUMN thread_id TEXT;
      ALTER TABLE workspaces ADD COLUMN summary_path TEXT;
      ALTER TABLE workspaces ADD COLUMN last_summarized_message_id TEXT;
    `,
  },
  {
    version: 24,
    // No REFERENCES threads(id) — same reasoning as version 23's
    // workspaces.thread_id above. resume_answer carries a HITL answer from
    // the /hitl route through task re-enqueue to the next executeTask() run
    // (task-execution.ts) — LangGraph can only unblock an interrupt() via
    // Command({ resume }), not a fresh message.
    sql: `
      ALTER TABLE tasks ADD COLUMN thread_id TEXT;
      ALTER TABLE tasks ADD COLUMN resume_answer TEXT;
    `,
  },
  {
    version: 25,
    sql: `
      ALTER TABLE projects ADD COLUMN close_intent TEXT;
      ALTER TABLE projects ADD COLUMN snapshot_path TEXT;
      ALTER TABLE projects ADD COLUMN close_progress TEXT;
    `,
  },
  {
    version: 26,
    sql: `
      ALTER TABLE task_queue ADD COLUMN pause_reason TEXT;
      ALTER TABLE task_queue ADD COLUMN paused_at TEXT;
    `,
  },
  {
    version: 27,
    // No REFERENCES threads(id) on parent_thread_id — same reasoning as
    // version 23/24 above. origin distinguishes an ordinary user-created
    // task from one spawned by the spawn_sub_agent tool; parent_thread_id/
    // dispatch_group_id/role are only ever set together, all null for
    // origin='user'. See docs/superpowers/specs/2026-09-09-sub-agent-tooling-design.md.
    sql: `
      ALTER TABLE tasks ADD COLUMN origin TEXT NOT NULL DEFAULT 'user';
      ALTER TABLE tasks ADD COLUMN parent_thread_id TEXT;
      ALTER TABLE tasks ADD COLUMN dispatch_group_id TEXT;
      ALTER TABLE tasks ADD COLUMN role TEXT;
    `,
  },
  {
    version: 31,
    // task_dependencies gates a task from auto-ready/enqueue until its
    // dependencies are satisfied (see isTaskReady()/releaseEligibleDependents()
    // below). REFERENCES tasks(id) is safe here (unlike a REFERENCES column
    // added via ALTER TABLE, per the version 23 comment above) since this is
    // a fresh CREATE TABLE, not an ALTER. blocked_reason carries why a task
    // is 'blocked' when that's due to a broken dependency — distinct from
    // task_queue.pause_reason, which only exists for a task that actually
    // reached 'running' and then got paused (a dependency-blocked task never
    // gets that far, so has no queue row to carry a reason on). See
    // docs/superpowers/specs/2026-09-22-task-dependencies-design.md.
    sql: `
      CREATE TABLE IF NOT EXISTS task_dependencies (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        task_id TEXT NOT NULL REFERENCES tasks(id),
        depends_on_task_id TEXT NOT NULL REFERENCES tasks(id),
        require_success INTEGER NOT NULL DEFAULT 1,
        while_blocked INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL,
        UNIQUE(task_id, depends_on_task_id),
        CHECK(task_id != depends_on_task_id)
      );
      CREATE INDEX idx_task_dependencies_task_id ON task_dependencies(task_id);
      CREATE INDEX idx_task_dependencies_depends_on ON task_dependencies(depends_on_task_id);
      ALTER TABLE tasks ADD COLUMN blocked_reason TEXT;
    `,
  },
  {
    version: 32,
    // Every run now gets its own thread. Rows still open when this migration
    // runs ('running' from a crash, or 'paused' on a user pause / HITL
    // answer) already have a LangGraph checkpoint in the thread the old
    // resolution used — the workspace's shared thread, or the task's own
    // thread — so they're backfilled with it, and resume exactly where they
    // left off. Finished rows keep thread_id NULL: they predate per-run
    // threads and are excluded from run history's transcript links.
    sql: `
      ALTER TABLE task_queue ADD COLUMN thread_id TEXT;
      ALTER TABLE task_queue ADD COLUMN summary TEXT;
      ALTER TABLE task_queue ADD COLUMN trigger_source TEXT NOT NULL DEFAULT 'manual';
      ALTER TABLE task_queue ADD COLUMN scheduled_for TEXT;
      UPDATE task_queue
         SET thread_id = (
           SELECT COALESCE(workspaces.thread_id, tasks.thread_id)
             FROM tasks
             LEFT JOIN workspaces ON workspaces.id = tasks.workspace_id
            WHERE tasks.id = task_queue.task_id
         )
       WHERE status IN ('running', 'paused');
      CREATE INDEX IF NOT EXISTS idx_task_queue_task_id ON task_queue(task_id);
      CREATE INDEX IF NOT EXISTS idx_task_queue_thread_id ON task_queue(thread_id);
    `,
  },
  {
    version: 36,
    // How a *task* was created (webhook task creation, #252) — distinct
    // from task_queue.trigger_source above, which records what started a
    // *run*. 'schedule'/'catch_up' etc. don't apply to creation, so this is
    // deliberately a narrower type than TriggerSource.
    sql: `ALTER TABLE tasks ADD COLUMN trigger_source TEXT NOT NULL DEFAULT 'user';`,
  },
];

// ---------------------------------------------------------------------------
// WorkspaceStore
// ---------------------------------------------------------------------------

// One automatic retry after a crash, then escalate the task to the user
// rather than retrying forever. See recoverRunningQueueEntries() below.
const MAX_QUEUE_RECOVERY_ATTEMPTS = 1;

export class WorkspaceStore extends BaseStore {
  // Origin='agent' rows recoverRunningQueueEntries() marks failed after
  // exhausting retries, collected here rather than notified immediately.
  // recoverRunningQueueEntries() runs synchronously from the constructor —
  // before bootWorkspaceStore() has even assigned the module-level _store
  // singleton, let alone before initChatAgent() sets up the checkpointer a
  // completion notification's agent build needs. Boot wiring (index.ts)
  // drains this once the full boot sequence completes and delivers each via
  // deliverSubAgentCompletion() — see docs/superpowers/specs/2026-09-09-sub-agent-tooling-design.md §7.
  private _pendingSubAgentCrashNotifications: Task[] = [];

  constructor(db: SqliteDatabase) {
    super(db);
    this.runMigrations(MIGRATIONS);
    this.recoverRunningQueueEntries();
  }

  drainPendingSubAgentCrashNotifications(): Task[] {
    const pending = this._pendingSubAgentCrashNotifications;
    this._pendingSubAgentCrashNotifications = [];
    return pending;
  }

  // On server start, any queue entry stuck in `running` (from a crash) is
  // reset to `pending` so the scheduler can pick it up again (R5) — but only
  // once. A queue entry that crashes a second time in a row is assumed to be
  // a real, unrecoverable failure rather than a transient one, and is handed
  // back to the user instead of retried forever.
  private recoverRunningQueueEntries(): void {
    const stuck = this.db
      .prepare(
        `SELECT task_queue.id AS id, task_queue.task_id AS task_id,
                task_queue.recovery_attempts AS recovery_attempts, tasks.origin AS origin,
                task_queue.trigger_source AS trigger_source, tasks.trigger_type AS trigger_type
         FROM task_queue
         JOIN tasks ON tasks.id = task_queue.task_id
         WHERE task_queue.status = 'running'`,
      )
      .all() as {
      id: string;
      task_id: string;
      recovery_attempts: number;
      origin: 'user' | 'agent';
      trigger_source: TriggerSource;
      trigger_type: TriggerType;
    }[];

    const now = new Date().toISOString();
    const retry = this.db.prepare(
      `UPDATE task_queue SET status = 'pending', started_at = NULL, recovery_attempts = recovery_attempts + 1 WHERE id = ?`,
    );
    const giveUp = this.db.prepare(
      `UPDATE task_queue SET status = 'failed', finished_at = ?, summary = 'Run failed after crash recovery.' WHERE id = ?`,
    );
    const mirrorReady = this.db.prepare(
      `UPDATE tasks SET status = 'ready', updated_at = ? WHERE id = ? AND status = 'running'`,
    );
    // origin='user': hand back to the human via /hitl-style escalation —
    // there's no one else to resolve it. origin='agent' has no human on the
    // other end, so it's just marked failed and queued for the
    // spawn_sub_agent completion-notification flow instead (see
    // drainPendingSubAgentCrashNotifications() above).
    const mirrorEscalate = this.db.prepare(
      `UPDATE tasks SET status = 'waiting_on_user', assigned_to = 'user', updated_at = ? WHERE id = ? AND status = 'running'`,
    );
    const mirrorFail = this.db.prepare(
      `UPDATE tasks SET status = 'failed', updated_at = ? WHERE id = ? AND status = 'running'`,
    );

    for (const row of stuck) {
      if (row.recovery_attempts < MAX_QUEUE_RECOVERY_ATTEMPTS) {
        retry.run(row.id);
        mirrorReady.run(now, row.task_id);
      } else if (row.origin === 'agent') {
        giveUp.run(now, row.id);
        mirrorFail.run(now, row.task_id);
        const task = this.getTask(row.task_id);
        if (task) this._pendingSubAgentCrashNotifications.push(task);
      } else if (
        isCronTrigger(row.trigger_type) &&
        (row.trigger_source === 'schedule' || row.trigger_source === 'catch_up')
      ) {
        // A run the schedule started has no one waiting on it — escalating
        // it to the user would park the schedule until someone noticed. It
        // settles as a failed run instead, which counts toward auto-pause.
        giveUp.run(now, row.id);
        this.settleTaskAfterRun(row.task_id, row.trigger_source, 'failed', now);
      } else {
        giveUp.run(now, row.id);
        mirrorEscalate.run(now, row.task_id);
      }
    }
  }

  // -------------------------------------------------------------------------
  // Workspaces
  // -------------------------------------------------------------------------

  listWorkspaces(): Workspace[] {
    const rows = this.db
      .prepare(`SELECT * FROM workspaces ORDER BY updated_at DESC`)
      .all() as RawWorkspaceRow[];
    return rows.map(mapWorkspace);
  }

  getWorkspace(id: string): Workspace | null {
    const row = this.db.prepare(`SELECT * FROM workspaces WHERE id = ?`).get(id) as
      RawWorkspaceRow | undefined;
    return row ? mapWorkspace(row) : null;
  }

  // Used to resolve a sub-agent completion notification's parent agent when
  // the parent thread is type='workspace-chat' — see task-execution.ts.
  getWorkspaceByThreadId(threadId: string): Workspace | null {
    const row = this.db.prepare(`SELECT * FROM workspaces WHERE thread_id = ?`).get(threadId) as
      RawWorkspaceRow | undefined;
    return row ? mapWorkspace(row) : null;
  }

  findWorkspaceByName(name: string): Workspace | null {
    const row = this.db
      .prepare(`SELECT * FROM workspaces WHERE LOWER(name) = LOWER(?) LIMIT 1`)
      .get(name) as RawWorkspaceRow | undefined;
    return row ? mapWorkspace(row) : null;
  }

  createWorkspace(input: NewWorkspaceInput): Workspace {
    const id = randomUUID();
    const now = new Date().toISOString();
    this.db
      .prepare(
        `INSERT INTO workspaces
           (id, name, description, goal, location, remote_url, javascript, python, git, wiki_id, system_prompt, created_at, updated_at, last_change)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        id,
        input.name,
        input.description ?? null,
        input.goal ?? null,
        input.location,
        input.remoteUrl ?? null,
        input.javascript ? 1 : 0,
        input.python ? 1 : 0,
        input.git ? 1 : 0,
        input.wikiId ?? null,
        input.systemPrompt ?? null,
        now,
        now,
        now,
      );
    return this.getWorkspace(id)!;
  }

  patchWorkspace(id: string, patch: PatchWorkspaceInput): Workspace | null {
    const sets: string[] = [];
    const values: unknown[] = [];

    if (patch.name !== undefined) {
      sets.push('name = ?');
      values.push(patch.name);
    }
    if (patch.description !== undefined) {
      sets.push('description = ?');
      values.push(patch.description);
    }
    if (patch.goal !== undefined) {
      sets.push('goal = ?');
      values.push(patch.goal);
    }
    if (patch.remoteUrl !== undefined) {
      sets.push('remote_url = ?');
      values.push(patch.remoteUrl);
    }
    if (patch.javascript !== undefined) {
      sets.push('javascript = ?');
      values.push(patch.javascript ? 1 : 0);
    }
    if (patch.python !== undefined) {
      sets.push('python = ?');
      values.push(patch.python ? 1 : 0);
    }
    if (patch.git !== undefined) {
      sets.push('git = ?');
      values.push(patch.git ? 1 : 0);
    }
    if (patch.wikiId !== undefined) {
      sets.push('wiki_id = ?');
      values.push(patch.wikiId);
    }
    if (patch.systemPrompt !== undefined) {
      sets.push('system_prompt = ?');
      values.push(patch.systemPrompt);
    }
    if (patch.threadId !== undefined) {
      sets.push('thread_id = ?');
      values.push(patch.threadId);
    }
    if (patch.summaryPath !== undefined) {
      sets.push('summary_path = ?');
      values.push(patch.summaryPath);
    }
    if (patch.lastSummarizedMessageId !== undefined) {
      sets.push('last_summarized_message_id = ?');
      values.push(patch.lastSummarizedMessageId);
    }

    if (sets.length === 0) return this.getWorkspace(id);

    const now = new Date().toISOString();
    sets.push('updated_at = ?');
    values.push(now);

    const result = this.db
      .prepare(`UPDATE workspaces SET ${sets.join(', ')} WHERE id = ?`)
      .run(...values, id);
    if (result.changes === 0) return null;
    return this.getWorkspace(id);
  }

  deleteWorkspace(id: string): boolean {
    const doDelete = this.db.transaction(() => {
      // Remove task_queue entries, then tasks, then the project row (all FK'd to this workspace).
      this.db
        .prepare(
          `DELETE FROM task_queue WHERE task_id IN (SELECT id FROM tasks WHERE workspace_id = ?)`,
        )
        .run(id);
      this.db
        .prepare(
          `DELETE FROM task_dependencies
           WHERE task_id IN (SELECT id FROM tasks WHERE workspace_id = ?)
              OR depends_on_task_id IN (SELECT id FROM tasks WHERE workspace_id = ?)`,
        )
        .run(id, id);
      this.db.prepare(`DELETE FROM tasks WHERE workspace_id = ?`).run(id);
      this.db.prepare(`DELETE FROM projects WHERE workspace_id = ?`).run(id);
      return this.db.prepare(`DELETE FROM workspaces WHERE id = ?`).run(id);
    });
    const result = doDelete();
    return result.changes > 0;
  }

  touchWorkspace(id: string): void {
    const now = new Date().toISOString();
    this.db
      .prepare(`UPDATE workspaces SET last_change = ?, updated_at = ? WHERE id = ?`)
      .run(now, now, id);
  }

  // -------------------------------------------------------------------------
  // Projects
  // -------------------------------------------------------------------------

  listProjects(): Array<Workspace & { project: Project }> {
    const workspaces = this.db
      .prepare(
        `SELECT w.*, p.win_condition, p.due_at AS p_due_at, p.status AS p_status, p.closed_at,
                p.close_intent, p.snapshot_path, p.close_progress
         FROM workspaces w
         INNER JOIN projects p ON p.workspace_id = w.id
         ORDER BY w.updated_at DESC`,
      )
      .all() as Array<
      RawWorkspaceRow & {
        win_condition: string;
        p_due_at: string | null;
        p_status: 'active' | 'closing' | 'closed' | 'abandoned';
        closed_at: string | null;
        close_intent: 'close' | 'abandon' | null;
        snapshot_path: string | null;
        close_progress: string | null;
      }
    >;

    return workspaces.map((row) => ({
      ...mapWorkspace(row),
      project: {
        id: row.id,
        workspaceId: row.id,
        winCondition: row.win_condition,
        dueAt: row.p_due_at,
        status: row.p_status,
        closedAt: row.closed_at,
        closeIntent: row.close_intent,
        snapshotPath: row.snapshot_path,
        closeProgress: row.close_progress
          ? (JSON.parse(row.close_progress) as CloseProgress)
          : null,
      },
    }));
  }

  getProject(workspaceId: string): Project | null {
    const row = this.db
      .prepare(`SELECT * FROM projects WHERE workspace_id = ?`)
      .get(workspaceId) as RawProjectRow | undefined;
    return row ? mapProject(row) : null;
  }

  // Creates workspace + project rows in a single transaction (R1).
  createProject(input: NewProjectInput): { workspace: Workspace; project: Project } {
    const id = input.id;
    const now = new Date().toISOString();

    const doCreate = this.db.transaction(() => {
      this.db
        .prepare(
          `INSERT INTO workspaces
             (id, name, description, goal, location, remote_url, javascript, python, git, wiki_id, system_prompt, created_at, updated_at, last_change)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        )
        .run(
          id,
          input.name,
          input.description ?? null,
          input.goal ?? null,
          input.location,
          input.remoteUrl ?? null,
          input.javascript ? 1 : 0,
          input.python ? 1 : 0,
          input.git ? 1 : 0,
          input.wikiId ?? null,
          input.systemPrompt ?? null,
          now,
          now,
          now,
        );

      this.db
        .prepare(
          `INSERT INTO projects (id, workspace_id, win_condition, due_at, status)
           VALUES (?, ?, ?, ?, 'active')`,
        )
        .run(id, id, input.winCondition, input.dueAt ?? null);
    });

    doCreate();

    return {
      workspace: this.getWorkspace(id)!,
      project: this.getProject(id)!,
    };
  }

  patchProject(workspaceId: string, patch: PatchProjectInput): Project | null {
    this.patchWorkspace(workspaceId, patch);

    const sets: string[] = [];
    const values: unknown[] = [];

    if (patch.winCondition !== undefined) {
      sets.push('win_condition = ?');
      values.push(patch.winCondition);
    }
    if (patch.dueAt !== undefined) {
      sets.push('due_at = ?');
      values.push(patch.dueAt);
    }
    if (patch.closeProgress !== undefined) {
      // Shallow-merge with whatever's already stored so a PATCH from one
      // close-wizard step (e.g. mergeSelections) never clobbers a key
      // written by another step (e.g. dependencySelections).
      const existing = this.getProject(workspaceId);
      const merged: CloseProgress = { ...(existing?.closeProgress ?? {}), ...patch.closeProgress };
      sets.push('close_progress = ?');
      values.push(JSON.stringify(merged));
    }

    if (sets.length > 0) {
      this.db
        .prepare(`UPDATE projects SET ${sets.join(', ')} WHERE workspace_id = ?`)
        .run(...values, workspaceId);
    }

    return this.getProject(workspaceId);
  }

  /** Look up the project (if any) that owns the wiki domain `wikiId`, via
   * the owning workspace's wiki_id. Used to gate writes against a domain
   * belonging to a closed/abandoned project (R11). */
  getProjectByWikiId(wikiId: string): Project | null {
    const row = this.db
      .prepare(
        `SELECT p.* FROM projects p
         JOIN workspaces w ON w.id = p.workspace_id
         WHERE w.wiki_id = ?`,
      )
      .get(wikiId) as RawProjectRow | undefined;
    return row ? mapProject(row) : null;
  }

  /** Every wiki domain id currently bound to at least one workspace
   * (project or not). A bound wiki belongs to its workspace(s): other
   * workspaces may not write to it — see services/wiki-write-scope.ts. */
  listBoundWikiIds(): string[] {
    const rows = this.db
      .prepare(`SELECT DISTINCT wiki_id FROM workspaces WHERE wiki_id IS NOT NULL`)
      .all() as { wiki_id: string }[];
    return rows.map((r) => r.wiki_id);
  }

  /** Move a project into the closing state. Only succeeds from 'active'. */
  closeProject(workspaceId: string, intent: 'close' | 'abandon'): Project | null {
    const result = this.db
      .prepare(
        `UPDATE projects SET status = 'closing', close_intent = ? WHERE workspace_id = ? AND status = 'active'`,
      )
      .run(intent, workspaceId);
    if (result.changes === 0) return null;
    return this.getProject(workspaceId);
  }

  /** Idempotent — a second call with the same or a different path still
   * succeeds; callers that want "only once" check project.snapshotPath first. */
  setSnapshotPath(workspaceId: string, snapshotPath: string): Project | null {
    const result = this.db
      .prepare(`UPDATE projects SET snapshot_path = ? WHERE workspace_id = ?`)
      .run(snapshotPath, workspaceId);
    if (result.changes === 0) return null;
    return this.getProject(workspaceId);
  }

  /** Terminal transition out of 'closing'. Clears close_progress — no longer
   * needed once the project is closed/abandoned. */
  completeClose(workspaceId: string, status: 'closed' | 'abandoned'): Project | null {
    const now = new Date().toISOString();
    const result = this.db
      .prepare(
        `UPDATE projects SET status = ?, closed_at = ?, close_progress = NULL
         WHERE workspace_id = ? AND status = 'closing'`,
      )
      .run(status, now, workspaceId);
    if (result.changes === 0) return null;
    return this.getProject(workspaceId);
  }

  // -------------------------------------------------------------------------
  // Tasks
  // -------------------------------------------------------------------------

  listTasks(filters: TaskListFilters = {}): Task[] {
    const conditions: string[] = [];
    const values: unknown[] = [];

    if ('workspaceId' in filters) {
      if (filters.workspaceId === null) {
        conditions.push('workspace_id IS NULL');
      } else if (filters.workspaceId !== undefined) {
        conditions.push('workspace_id = ?');
        values.push(filters.workspaceId);
      }
    }

    if (filters.status !== undefined) {
      conditions.push('status = ?');
      values.push(filters.status);
    }

    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
    const rows = this.db
      .prepare(`SELECT * FROM tasks ${where} ORDER BY created_at DESC`)
      .all(...values) as RawTaskRow[];
    return rows.map(mapTask);
  }

  getTask(id: string): Task | null {
    const row = this.db.prepare(`SELECT * FROM tasks WHERE id = ?`).get(id) as
      RawTaskRow | undefined;
    return row ? mapTask(row) : null;
  }

  // The task that owns a type='task' thread — used to resolve a sub-agent
  // completion notification's parent agent when the parent thread is one.
  // Every run now has its own thread (task_queue.thread_id); tasks.thread_id
  // is only still consulted for legacy threads minted before per-run
  // threads existed.
  getTaskByThreadId(threadId: string): Task | null {
    const row = this.db
      .prepare(
        `SELECT tasks.* FROM task_queue
         JOIN tasks ON tasks.id = task_queue.task_id
         WHERE task_queue.thread_id = ?
         LIMIT 1`,
      )
      .get(threadId) as RawTaskRow | undefined;
    if (row) return mapTask(row);
    const legacy = this.db.prepare(`SELECT * FROM tasks WHERE thread_id = ?`).get(threadId) as
      RawTaskRow | undefined;
    return legacy ? mapTask(legacy) : null;
  }

  findTaskByWebhookToken(token: string): Task | null {
    const row = this.db
      .prepare(
        `SELECT * FROM tasks
         WHERE trigger_type = 'webhook'
           AND JSON_EXTRACT(trigger_config, '$.webhookToken') = ?
         LIMIT 1`,
      )
      .get(token) as RawTaskRow | undefined;
    return row ? mapTask(row) : null;
  }

  createTask(input: NewTaskInput): Task {
    const id = randomUUID();
    const now = new Date().toISOString();
    this.db
      .prepare(
        `INSERT INTO tasks
           (id, workspace_id, title, description, outcome, status, assigned_to, due_at, expires_at, trigger_type, trigger_config, tracker_type, tracker_id, plan, origin, trigger_source, parent_thread_id, dispatch_group_id, role, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, 'pending', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .run(
        id,
        input.workspaceId ?? null,
        input.title,
        input.description ?? null,
        input.outcome ?? null,
        input.assignedTo ?? null,
        input.dueAt ?? null,
        input.expiresAt ?? null,
        input.triggerType ?? 'manual',
        input.triggerConfig !== undefined ? JSON.stringify(input.triggerConfig) : null,
        input.trackerType ?? null,
        input.trackerId ?? null,
        input.plan ? JSON.stringify(input.plan) : null,
        input.origin ?? 'user',
        input.triggerSource ?? 'user',
        input.parentThreadId ?? null,
        input.dispatchGroupId ?? null,
        input.role ?? null,
        now,
        now,
      );
    return this.getTask(id)!;
  }

  patchTask(id: string, patch: PatchTaskInput): Task | null {
    const sets: string[] = [];
    const values: unknown[] = [];

    if (patch.workspaceId !== undefined) {
      sets.push('workspace_id = ?');
      values.push(patch.workspaceId);
    }
    if (patch.title !== undefined) {
      sets.push('title = ?');
      values.push(patch.title);
    }
    if (patch.description !== undefined) {
      sets.push('description = ?');
      values.push(patch.description);
    }
    if (patch.outcome !== undefined) {
      sets.push('outcome = ?');
      values.push(patch.outcome);
    }
    if (patch.status !== undefined) {
      sets.push('status = ?');
      values.push(patch.status);
    }
    if (patch.assignedTo !== undefined) {
      sets.push('assigned_to = ?');
      values.push(patch.assignedTo);
    }
    if (patch.dueAt !== undefined) {
      sets.push('due_at = ?');
      values.push(patch.dueAt);
    }
    if (patch.expiresAt !== undefined) {
      sets.push('expires_at = ?');
      values.push(patch.expiresAt);
    }
    if (patch.triggerType !== undefined) {
      sets.push('trigger_type = ?');
      values.push(patch.triggerType);
    }
    if (patch.triggerConfig !== undefined) {
      sets.push('trigger_config = ?');
      values.push(JSON.stringify(patch.triggerConfig));
    }
    if (patch.trackerType !== undefined) {
      sets.push('tracker_type = ?');
      values.push(patch.trackerType);
    }
    if (patch.trackerId !== undefined) {
      sets.push('tracker_id = ?');
      values.push(patch.trackerId);
    }
    if (patch.plan !== undefined) {
      sets.push('plan = ?');
      values.push(patch.plan ? JSON.stringify(patch.plan) : null);
    }
    if (patch.threadId !== undefined) {
      sets.push('thread_id = ?');
      values.push(patch.threadId);
    }
    if (patch.resumeAnswer !== undefined) {
      sets.push('resume_answer = ?');
      values.push(patch.resumeAnswer);
    }
    if (patch.blockedReason !== undefined) {
      sets.push('blocked_reason = ?');
      values.push(patch.blockedReason);
    }

    if (sets.length === 0) return this.getTask(id);

    const now = new Date().toISOString();
    sets.push('updated_at = ?');
    values.push(now);

    const result = this.db
      .prepare(`UPDATE tasks SET ${sets.join(', ')} WHERE id = ?`)
      .run(...values, id);
    if (result.changes === 0) return null;
    return this.getTask(id);
  }

  // Removes a task with its dependency edges and its run history
  // (task_queue rows FK'd to it — without this, any task that ever ran
  // failed to delete). Callers refuse to delete a task with an active run.
  deleteTask(id: string): boolean {
    return this.db.transaction(() => {
      this.db
        .prepare(`DELETE FROM task_dependencies WHERE task_id = ? OR depends_on_task_id = ?`)
        .run(id, id);
      this.db.prepare(`DELETE FROM task_queue WHERE task_id = ?`).run(id);
      const result = this.db.prepare(`DELETE FROM tasks WHERE id = ?`).run(id);
      return result.changes > 0;
    })();
  }

  // -------------------------------------------------------------------------
  // Task dependencies
  //
  // A task with one or more rows here (task_id = this task) cannot become
  // 'ready' until every row is satisfied — see isTaskReady()/
  // hasBrokenDependency()/releaseEligibleDependents(). Called from exactly
  // two choke points (completeQueueEntry, parkQueueEntry below) rather than
  // scattered call sites. See
  // docs/superpowers/specs/2026-09-22-task-dependencies-design.md.
  // -------------------------------------------------------------------------

  addTaskDependency(
    taskId: string,
    dependsOnTaskId: string,
    opts: { requireSuccess?: boolean; whileBlocked?: boolean } = {},
  ): TaskDependency {
    const now = new Date().toISOString();
    const result = this.db
      .prepare(
        `INSERT INTO task_dependencies (task_id, depends_on_task_id, require_success, while_blocked, created_at)
         VALUES (?, ?, ?, ?, ?)`,
      )
      .run(
        taskId,
        dependsOnTaskId,
        opts.requireSuccess === false ? 0 : 1,
        opts.whileBlocked ? 1 : 0,
        now,
      );
    const row = this.db
      .prepare(`SELECT * FROM task_dependencies WHERE id = ?`)
      .get(Number(result.lastInsertRowid)) as RawTaskDependencyRow;
    return mapTaskDependency(row);
  }

  removeTaskDependency(id: number): void {
    this.db.prepare(`DELETE FROM task_dependencies WHERE id = ?`).run(id);
  }

  // Outgoing — what this task depends on.
  listTaskDependencies(taskId: string): TaskDependency[] {
    const rows = this.db
      .prepare(`SELECT * FROM task_dependencies WHERE task_id = ?`)
      .all(taskId) as RawTaskDependencyRow[];
    return rows.map(mapTaskDependency);
  }

  // Incoming — who depends on this task.
  listDependents(taskId: string): TaskDependency[] {
    const rows = this.db
      .prepare(`SELECT * FROM task_dependencies WHERE depends_on_task_id = ?`)
      .all(taskId) as RawTaskDependencyRow[];
    return rows.map(mapTaskDependency);
  }

  // Outgoing edges for many tasks in one query, each with its target's
  // title/tracker/status and whether the edge is currently satisfied — the
  // Kanban board's "Waiting on …" badge and dependency_failed reason (see the
  // board-v2 design, §1.6). Tasks with no edges are absent from the map.
  listDependencyEdgesForTasks(taskIds: string[]): Map<string, DependencyEdgeSummary[]> {
    const result = new Map<string, DependencyEdgeSummary[]>();
    if (taskIds.length === 0) return result;
    const placeholders = taskIds.map(() => '?').join(', ');
    const rows = this.db
      .prepare(
        `SELECT task_dependencies.*, tasks.status AS target_status, tasks.title AS target_title,
                tasks.tracker_id AS target_tracker_id
         FROM task_dependencies
         JOIN tasks ON tasks.id = task_dependencies.depends_on_task_id
         WHERE task_dependencies.task_id IN (${placeholders})`,
      )
      .all(...taskIds) as (RawTaskDependencyRow & {
      target_status: TaskStatus;
      target_title: string;
      target_tracker_id: string | null;
    })[];
    for (const row of rows) {
      const dep = mapTaskDependency(row);
      const edges = result.get(dep.taskId) ?? [];
      edges.push({
        dependency: dep,
        target: {
          id: dep.dependsOnTaskId,
          title: row.target_title,
          trackerId: row.target_tracker_id,
          status: row.target_status,
        },
        satisfied: this.isEdgeSatisfied(dep, row.target_status),
      });
      result.set(dep.taskId, edges);
    }
    return result;
  }

  private loadDependencyEdges(
    taskId: string,
  ): Array<{ dep: TaskDependency; targetStatus: TaskStatus }> {
    const rows = this.db
      .prepare(
        `SELECT task_dependencies.*, tasks.status AS target_status
         FROM task_dependencies
         JOIN tasks ON tasks.id = task_dependencies.depends_on_task_id
         WHERE task_dependencies.task_id = ?`,
      )
      .all(taskId) as (RawTaskDependencyRow & { target_status: TaskStatus })[];
    return rows.map((row) => ({ dep: mapTaskDependency(row), targetStatus: row.target_status }));
  }

  private isEdgeSatisfied(dep: TaskDependency, targetStatus: TaskStatus): boolean {
    if (dep.whileBlocked && targetStatus === 'blocked') return true;
    if (dep.requireSuccess) return targetStatus === 'done';
    return targetStatus === 'done' || targetStatus === 'failed' || targetStatus === 'cancelled';
  }

  isTaskReady(taskId: string): boolean {
    return this.loadDependencyEdges(taskId).every(({ dep, targetStatus }) =>
      this.isEdgeSatisfied(dep, targetStatus),
    );
  }

  // A requireSuccess edge whose target is failed/cancelled can never become
  // satisfied (a task never leaves a terminal state on its own) — distinct
  // from isTaskReady() returning false, which just means "not yet".
  hasBrokenDependency(taskId: string): boolean {
    return this.loadDependencyEdges(taskId).some(
      ({ dep, targetStatus }) =>
        dep.requireSuccess && (targetStatus === 'failed' || targetStatus === 'cancelled'),
    );
  }

  // Re-evaluates every task waiting on changedTaskId, called right after
  // changedTaskId itself transitions to a status dependents might care about
  // (done/failed/cancelled via completeQueueEntry, or blocked via
  // parkQueueEntry). A dependent already past 'pending' was already released
  // (or taken over) earlier and is left alone here.
  releaseEligibleDependents(changedTaskId: string): void {
    for (const dependency of this.listDependents(changedTaskId)) {
      const dependentTask = this.getTask(dependency.taskId);
      if (!dependentTask || dependentTask.status !== 'pending') continue;

      if (this.hasBrokenDependency(dependency.taskId)) {
        this.patchTask(dependency.taskId, {
          status: 'blocked',
          blockedReason: 'dependency_failed',
        });
      } else if (this.isTaskReady(dependency.taskId)) {
        if (isCronTrigger(dependentTask.triggerType) && dependentTask.triggerConfig) {
          // A cron-triggered dependent goes onto its schedule instead of
          // into the queue once it's released — the cron registry (synced
          // by withCronResync after this run settles) is what actually
          // arms its timer. See cron-registry.ts's resyncAll().
          const status = statusForSavedSchedule(
            dependentTask.status,
            dependentTask.triggerType,
            dependentTask.triggerConfig as CronConfig,
            this.countScheduledRuns(dependency.taskId),
            new Date(),
          );
          if (status) this.patchTask(dependency.taskId, { status });
        } else {
          this.patchTask(dependency.taskId, { status: 'ready', assignedTo: 'agent' });
          this.enqueueTask(dependency.taskId);
        }
      }
    }
  }

  // -------------------------------------------------------------------------
  // Task queue
  // -------------------------------------------------------------------------

  listQueue(): TaskQueueEntry[] {
    const rows = this.db
      .prepare(
        `SELECT * FROM task_queue WHERE status IN ('pending', 'running', 'paused') ORDER BY position ASC`,
      )
      .all() as RawQueueRow[];
    return rows.map(mapQueueEntry);
  }

  enqueueTask(taskId: string, opts: EnqueueOptions = {}): TaskQueueEntry {
    const id = randomUUID();
    const now = new Date().toISOString();
    const posRow = this.db
      .prepare(
        `SELECT COALESCE(MAX(position), 0) + 1 AS next FROM task_queue WHERE status IN ('pending', 'running', 'paused')`,
      )
      .get() as { next: number };
    const position = posRow.next;

    this.db
      .prepare(
        `INSERT INTO task_queue (id, task_id, status, position, enqueued_at, trigger_source, scheduled_for)
         VALUES (?, ?, 'pending', ?, ?, ?, ?)`,
      )
      .run(id, taskId, position, now, opts.triggerSource ?? 'manual', opts.scheduledFor ?? null);

    const row = this.db.prepare(`SELECT * FROM task_queue WHERE id = ?`).get(id) as RawQueueRow;
    return mapQueueEntry(row);
  }

  getQueueEntry(id: string): TaskQueueEntry | null {
    const row = this.db.prepare(`SELECT * FROM task_queue WHERE id = ?`).get(id) as
      RawQueueRow | undefined;
    return row ? mapQueueEntry(row) : null;
  }

  // Records the thread a run executes in — set once, on the run's first
  // start (see task-execution.ts); a resumed run reuses it.
  setQueueEntryThread(id: string, threadId: string): void {
    this.db.prepare(`UPDATE task_queue SET thread_id = ? WHERE id = ?`).run(threadId, id);
  }

  // The one-line outcome of a settled run — complete_task's own summary, or
  // a system-written one for a run that never called it. Surfaced by run
  // history and the next run's kickoff message.
  setQueueEntrySummary(id: string, summary: string): void {
    this.db.prepare(`UPDATE task_queue SET summary = ? WHERE id = ?`).run(summary, id);
  }

  // Takes a queued-but-never-started task back out of the queue and returns
  // it to 'pending'. The pending row is deleted rather than marked
  // 'cancelled' (cf. detachQueueEntry) because it never ran, so it must not
  // show up in run history. Returns false, changing nothing, when the task
  // has no pending row — a running or paused run is stopped via pause /
  // cancel instead.
  dequeueTask(taskId: string): boolean {
    return this.db.transaction(() => {
      const row = this.db
        .prepare(`SELECT id FROM task_queue WHERE task_id = ? AND status = 'pending'`)
        .get(taskId) as { id: string } | undefined;
      if (!row) return false;
      this.db.prepare(`DELETE FROM task_queue WHERE id = ?`).run(row.id);
      this.patchTask(taskId, { status: 'pending' });
      return true;
    })();
  }

  // Moves a task's pending row to `index` (0-based) among the pending rows of
  // its own scope (workspace, or the Inbox). The scope's rows keep the same
  // set of position values, just reassigned in the new order, so rows from
  // other scopes stay exactly where they were in the global ordering.
  // Running and paused rows are never moved. Returns false if the task has
  // no pending row.
  reorderQueue(taskId: string, index: number): boolean {
    return this.db.transaction(() => {
      const rows = this.db
        .prepare(
          `SELECT task_queue.id AS id, task_queue.task_id AS task_id, task_queue.position AS position
           FROM task_queue
           JOIN tasks ON tasks.id = task_queue.task_id
           WHERE task_queue.status = 'pending'
             AND COALESCE(tasks.workspace_id, 'inbox') = (
               SELECT COALESCE(workspace_id, 'inbox') FROM tasks WHERE id = ?
             )
           ORDER BY task_queue.position ASC`,
        )
        .all(taskId) as { id: string; task_id: string; position: number }[];
      const from = rows.findIndex((r) => r.task_id === taskId);
      if (from === -1) return false;

      const positions = rows.map((r) => r.position);
      const reordered = [...rows];
      const moved = reordered.splice(from, 1)[0]!;
      const to = Math.max(0, Math.min(index, reordered.length));
      reordered.splice(to, 0, moved);

      const update = this.db.prepare(`UPDATE task_queue SET position = ? WHERE id = ?`);
      reordered.forEach((r, i) => update.run(positions[i], r.id));
      return true;
    })();
  }

  // For each task, how many of its most recent settled runs failed in a row
  // (0 when the latest settled run didn't fail), plus the newest failure's
  // summary — the board's "Retry · N attempts" line. One query for all tasks.
  // Tasks with no trailing failures are absent from the map.
  failedRunStreaks(taskIds: string[]): Map<string, FailedRunStreak> {
    const result = new Map<string, FailedRunStreak>();
    if (taskIds.length === 0) return result;
    const placeholders = taskIds.map(() => '?').join(', ');
    const rows = this.db
      .prepare(
        `WITH ranked AS (
           SELECT task_id, status, summary,
                  ROW_NUMBER() OVER (PARTITION BY task_id ORDER BY enqueued_at DESC, rowid DESC) AS rn
           FROM task_queue
           WHERE task_id IN (${placeholders}) AND status IN ('done', 'failed', 'cancelled')
         ),
         first_non_failed AS (
           SELECT task_id, MIN(rn) AS rn FROM ranked WHERE status != 'failed' GROUP BY task_id
         )
         SELECT ranked.task_id AS task_id, COUNT(*) AS attempts,
                MAX(CASE WHEN ranked.rn = 1 THEN ranked.summary END) AS last_summary
         FROM ranked
         LEFT JOIN first_non_failed ON first_non_failed.task_id = ranked.task_id
         WHERE ranked.status = 'failed'
           AND (first_non_failed.rn IS NULL OR ranked.rn < first_non_failed.rn)
         GROUP BY ranked.task_id`,
      )
      .all(...taskIds) as { task_id: string; attempts: number; last_summary: string | null }[];
    for (const row of rows) {
      result.set(row.task_id, { attempts: row.attempts, lastSummary: row.last_summary });
    }
    return result;
  }

  // Every run of a task, newest first. runNumber is the run's 1-based
  // position in enqueue order across ALL of the task's runs, so it stays
  // stable no matter which page is requested.
  listTaskRuns(taskId: string, opts: { limit?: number; offset?: number } = {}): TaskRun[] {
    const rows = this.db
      .prepare(
        `SELECT * FROM (
           SELECT task_queue.*, ROW_NUMBER() OVER (ORDER BY enqueued_at ASC, rowid ASC) AS run_number
           FROM task_queue WHERE task_id = ?
         )
         ORDER BY run_number DESC
         LIMIT ? OFFSET ?`,
      )
      .all(taskId, opts.limit ?? -1, opts.offset ?? 0) as (RawQueueRow & { run_number: number })[];
    return rows.map((row) => ({ ...mapQueueEntry(row), runNumber: row.run_number }));
  }

  getTaskRun(runId: string): TaskRun | null {
    const row = this.db
      .prepare(
        `SELECT * FROM (
           SELECT task_queue.*, ROW_NUMBER() OVER (
             PARTITION BY task_id ORDER BY enqueued_at ASC, rowid ASC
           ) AS run_number
           FROM task_queue
           WHERE task_id = (SELECT task_id FROM task_queue WHERE id = ?)
         )
         WHERE id = ?`,
      )
      .get(runId, runId) as (RawQueueRow & { run_number: number }) | undefined;
    return row ? { ...mapQueueEntry(row), runNumber: row.run_number } : null;
  }

  // How many runs a cron schedule has started (schedule + catch-up) — what a
  // cron_repeat's maxIterations counts. Manual "Run now" runs don't count.
  countScheduledRuns(taskId: string): number {
    const row = this.db
      .prepare(
        `SELECT COUNT(*) AS n FROM task_queue
         WHERE task_id = ? AND trigger_source IN ('schedule', 'catch_up')`,
      )
      .get(taskId) as { n: number };
    return row.n;
  }

  getTaskRunByThreadId(threadId: string): TaskRun | null {
    const row = this.db
      .prepare(`SELECT id FROM task_queue WHERE thread_id = ? LIMIT 1`)
      .get(threadId) as { id: string } | undefined;
    return row ? this.getTaskRun(row.id) : null;
  }

  // Creates one origin='agent' task row (spawn_sub_agent's dispatch unit)
  // and enqueues it in a single transaction. dispatchGroupId is minted by
  // the caller (the spawn_sub_agent tool), not here — it's shared across
  // every sibling spawned from one same-turn batch of tool calls, and this
  // method only ever creates one row per call. Mirrors the status='ready'/
  // assigned_to='agent' shape patchTaskHandler's R14 rule uses for ordinary
  // tasks, since dequeueNext() itself only looks at task_queue rows, not
  // tasks.status, but the task list/UI still expects a coherent status.
  createSubAgentTask(input: {
    role: string;
    goal: string;
    parentThreadId: string;
    dispatchGroupId: string;
    workspaceId?: string | null;
  }): Task {
    return this.db.transaction(() => {
      const task = this.createTask({
        workspaceId: input.workspaceId ?? null,
        title: input.goal,
        origin: 'agent',
        parentThreadId: input.parentThreadId,
        dispatchGroupId: input.dispatchGroupId,
        role: input.role,
      });
      this.patchTask(task.id, { status: 'ready', assignedTo: 'agent' });
      this.enqueueTask(task.id, { triggerSource: 'agent' });
      return this.getTask(task.id)!;
    })();
  }

  // Creates a batch of ordinary (origin='user') task rows in one
  // transaction — all rows land or none do. A zero-dependency row is forced
  // straight to status='ready'/assigned_to='agent' and enqueued immediately,
  // mirroring createSubAgentTask()'s create->patch->enqueue shape rather
  // than trusting callers to pass the right status/assignedTo combination on
  // NewTaskInput (which has no status field at all — createTask() alone can
  // only ever insert 'pending') — unless it carries a cron trigger, in which
  // case it goes onto its schedule ('scheduled') instead, same as a
  // REST-created cron task (cron-config.ts's statusForSavedSchedule). Used
  // by the create_tasks chat tool to turn an approved plan into queued (or
  // scheduled), autonomously-executing work in one call. dependsOnIndexes
  // references another task by its position in this same `inputs` array
  // (not a real task id, which doesn't exist until after the insert below)
  // — only earlier indices are allowed, which alone rules out any cycle
  // within one batch without needing a graph traversal. A task with one or
  // more dependencies is left at createTask()'s default 'pending' instead of
  // being readied/scheduled/enqueued — see releaseEligibleDependents() for
  // how it's later picked up (readied, or scheduled if it's a cron task)
  // once its dependencies are satisfied.
  createTasks(inputs: (NewTaskInput & { dependsOnIndexes?: number[] })[]): Task[] {
    return this.db.transaction(() => {
      inputs.forEach((input, i) => {
        for (const depIndex of input.dependsOnIndexes ?? []) {
          if (!Number.isInteger(depIndex) || depIndex < 0 || depIndex >= i) {
            throw new Error(
              `Task ${i + 1}'s dependsOnIndexes must reference an earlier task in the same batch (got index ${depIndex}).`,
            );
          }
        }
      });

      const created = inputs.map((input) => this.createTask(input));

      inputs.forEach((input, i) => {
        for (const depIndex of input.dependsOnIndexes ?? []) {
          this.addTaskDependency(created[i]!.id, created[depIndex]!.id);
        }
      });

      return created.map((task) => {
        if (this.listTaskDependencies(task.id).length === 0) {
          if (isCronTrigger(task.triggerType) && task.triggerConfig) {
            // A cron-triggered task goes straight onto its schedule instead
            // of the queue — the caller (create_tasks) is responsible for
            // syncing the cron registry afterwards so its timer gets armed.
            const status = statusForSavedSchedule(
              task.status,
              task.triggerType,
              task.triggerConfig as CronConfig,
              this.countScheduledRuns(task.id),
              new Date(),
            );
            if (status) this.patchTask(task.id, { status });
          } else {
            this.patchTask(task.id, { status: 'ready', assignedTo: 'agent' });
            this.enqueueTask(task.id, { triggerSource: 'chat' });
          }
        }
        return this.getTask(task.id)!;
      });
    })();
  }

  // All origin='agent' rows sharing dispatchGroupId whose task_queue entry
  // hasn't reached a terminal state yet — used to compute remainingCount for
  // a completion-notification turn (see task-execution.ts's
  // deliverSubAgentCompletion()). A task with no queue row yet (impossible
  // in practice — createSubAgentTask() always enqueues immediately) would
  // not count as pending, which is fine: it can't happen.
  countPendingSiblings(dispatchGroupId: string, excludingTaskId: string): number {
    const row = this.db
      .prepare(
        `SELECT COUNT(*) AS n
         FROM tasks
         JOIN task_queue ON task_queue.task_id = tasks.id
         WHERE tasks.dispatch_group_id = ?
           AND tasks.id != ?
           AND task_queue.status IN ('pending', 'running', 'paused')`,
      )
      .get(dispatchGroupId, excludingTaskId) as { n: number };
    return row.n;
  }

  // Scope-aware: scans pending entries in position order and dispatches the
  // first one whose scope (COALESCE(tasks.workspace_id, 'inbox')) has no
  // running entry yet — not necessarily the globally-oldest entry. Lets an
  // Inbox task and a workspace task (or two unrelated workspaces) run
  // concurrently instead of enforcing one global "running" slot. See
  // docs/superpowers/specs/2026-09-09-task-queue-serialization-design.md.
  dequeueNext(): (TaskQueueEntry & { task: Task }) | null {
    const pending = this.db
      .prepare(
        `SELECT task_queue.*, tasks.workspace_id AS task_workspace_id, tasks.origin AS task_origin
         FROM task_queue
         JOIN tasks ON tasks.id = task_queue.task_id
         WHERE task_queue.status = 'pending'
         ORDER BY task_queue.position ASC`,
      )
      .all() as (RawQueueRow & {
      task_workspace_id: string | null;
      task_origin: 'user' | 'agent';
    })[];
    if (pending.length === 0) return null;

    // A scope is occupied by a 'running' task_queue row, or by a task still
    // sitting at 'waiting_on_user' — the interrupt (HITL approval) path in
    // task-execution.ts closes the queue row ('done') before the task
    // itself settles at 'waiting_on_user', so checking task_queue.status
    // alone would read the scope as free the instant that row closes, even
    // though the task is only paused, not finished, and still owns the
    // scope's shared thread. Sourcing straight from `tasks` catches both
    // cases without a join. origin='agent' (spawn_sub_agent) rows never
    // occupy or contend for a scope slot — see
    // docs/superpowers/specs/2026-09-09-sub-agent-tooling-design.md §2.
    const runningScopes = new Set(
      (
        this.db
          .prepare(
            `SELECT COALESCE(workspace_id, 'inbox') AS scope
             FROM tasks
             WHERE status IN ('running', 'waiting_on_user') AND origin != 'agent'`,
          )
          .all() as { scope: string }[]
      ).map((r) => r.scope),
    );

    const row = pending.find(
      (r) => r.task_origin === 'agent' || !runningScopes.has(r.task_workspace_id ?? 'inbox'),
    );
    if (!row) return null;

    const now = new Date().toISOString();
    this.db
      .prepare(`UPDATE task_queue SET status = 'running', started_at = ? WHERE id = ?`)
      .run(now, row.id);
    this.db
      .prepare(`UPDATE tasks SET status = 'running', updated_at = ? WHERE id = ?`)
      .run(now, row.task_id);

    const task = this.getTask(row.task_id);
    if (!task) return null;

    return { ...mapQueueEntry({ ...row, status: 'running', started_at: now }), task };
  }

  completeQueueEntry(id: string, outcome: 'done' | 'failed' | 'cancelled'): void {
    const now = new Date().toISOString();
    this.db
      .prepare(`UPDATE task_queue SET status = ?, finished_at = ? WHERE id = ?`)
      .run(outcome, now, id);

    const entry = this.db
      .prepare(`SELECT task_id, trigger_source FROM task_queue WHERE id = ?`)
      .get(id) as { task_id: string; trigger_source: TriggerSource } | undefined;
    if (entry) this.settleTaskAfterRun(entry.task_id, entry.trigger_source, outcome, now);
  }

  // Mirrors a finished run onto its task. An ordinary task takes the run's
  // outcome as its status; a cron task is settled by the schedule rules
  // (cron-settlement.ts) — typically back to 'scheduled' — and its failure
  // counter/auto-pause are written back into its trigger_config.
  private settleTaskAfterRun(
    taskId: string,
    source: TriggerSource,
    outcome: 'done' | 'failed' | 'cancelled',
    now: string,
  ): void {
    const task = this.getTask(taskId);
    if (task && isCronTrigger(task.triggerType) && task.triggerConfig) {
      const settled = settleCronRun({
        type: task.triggerType,
        config: task.triggerConfig as CronConfig,
        source,
        outcome,
        iterationCount: this.countScheduledRuns(taskId),
        now: new Date(now),
      });
      this.db
        .prepare(`UPDATE tasks SET status = ?, trigger_config = ?, updated_at = ? WHERE id = ?`)
        .run(settled.status, JSON.stringify(settled.config), now, taskId);
    } else {
      this.db
        .prepare(`UPDATE tasks SET status = ?, updated_at = ? WHERE id = ?`)
        .run(outcome, now, taskId);
    }
    this.releaseEligibleDependents(taskId);
  }

  // Enqueues one scheduled (or catch-up) run of a cron task, atomically, if
  // and only if the task is idle on its schedule: status 'scheduled' and
  // enabled. Anything else — already queued, running, waiting on the user,
  // paused, turned off, deleted — is a skipped fire, returned as null. The
  // fire time is recorded as lastFiredAt, which is what catch-up and the
  // one-shot "already fired" check read.
  fireCronTask(
    taskId: string,
    scheduledFor: string,
    source: 'schedule' | 'catch_up',
  ): TaskQueueEntry | null {
    return this.db.transaction(() => {
      const task = this.getTask(taskId);
      if (!task || !isCronTrigger(task.triggerType) || task.status !== 'scheduled') return null;
      const config = task.triggerConfig as CronConfig | null;
      if (!config?.enabled) return null;
      this.patchTask(taskId, {
        status: 'ready',
        assignedTo: 'agent',
        triggerConfig: { ...config, lastFiredAt: scheduledFor },
      });
      return this.enqueueTask(taskId, { triggerSource: source, scheduledFor });
    })();
  }

  // Every cron task waiting on its schedule — what the registry arms on boot.
  listScheduledTasks(): Task[] {
    const rows = this.db
      .prepare(
        `SELECT * FROM tasks
         WHERE status = 'scheduled' AND trigger_type IN ('cron_once', 'cron_repeat')`,
      )
      .all() as RawTaskRow[];
    return rows.map(mapTask);
  }

  // User-initiated Pause: parks the row (status 'paused', tagged
  // pause_reason 'user') and additionally parks the task itself at
  // 'blocked'.
  parkQueueEntry(id: string): void {
    const now = new Date().toISOString();
    this.db
      .prepare(
        `UPDATE task_queue SET status = 'paused', pause_reason = 'user', paused_at = ? WHERE id = ?`,
      )
      .run(now, id);
    const row = this.db.prepare(`SELECT task_id FROM task_queue WHERE id = ?`).get(id) as
      { task_id: string } | undefined;
    if (row) {
      this.db
        .prepare(`UPDATE tasks SET status = 'blocked', updated_at = ? WHERE id = ?`)
        .run(now, row.task_id);
      // Only a whileBlocked edge can be satisfied by this transition —
      // isTaskReady()'s per-edge check already handles that; a plain
      // requireSuccess edge just isn't satisfied yet.
      this.releaseEligibleDependents(row.task_id);
    }
  }

  // HITL approval pause: parks the row (status 'paused', tagged
  // pause_reason 'chat' — the existing 'chat'/'user' pauseReason union was
  // already carrying this case in reserve) and lands the task at
  // 'waiting_on_user'/'user', not 'blocked' — this is a different pause
  // than parkQueueEntry's user-initiated one. Deliberately does NOT call
  // releaseEligibleDependents(): a dependency edge is only satisfied by
  // 'blocked' (whileBlocked) or a terminal state, neither of which applies
  // to a task merely waiting on an approval answer.
  //
  // Keeping the row alive (rather than completeQueueEntry()'s 'done', which
  // discards it) is what lets the eventual resume reuse resumePausedEntry()
  // below instead of enqueueTask() — a fresh enqueueTask() call always
  // appends at the back of the queue, which lets every task still pending
  // in the same scope cut in front of a task that already started and is
  // merely waiting on a human answer. See
  // docs/superpowers/specs/2026-09-22-task-dependencies-design.md's related
  // discussion of scope occupancy for the same underlying failure mode.
  parkQueueEntryForHitl(id: string): void {
    const now = new Date().toISOString();
    this.db
      .prepare(
        `UPDATE task_queue SET status = 'paused', pause_reason = 'chat', paused_at = ? WHERE id = ?`,
      )
      .run(now, id);
    const row = this.db.prepare(`SELECT task_id FROM task_queue WHERE id = ?`).get(id) as
      { task_id: string } | undefined;
    if (row) {
      this.db
        .prepare(
          `UPDATE tasks SET status = 'waiting_on_user', assigned_to = 'user', updated_at = ? WHERE id = ?`,
        )
        .run(now, row.task_id);
    }
  }

  // Queue-only cleanup for a take-over: retires the row but deliberately
  // never touches `tasks` — the take-over route handler already committed
  // tasks.status/assigned_to synchronously before this runs (see
  // tasks.handlers.ts), and this must not clobber that.
  detachQueueEntry(id: string): void {
    const now = new Date().toISOString();
    this.db
      .prepare(`UPDATE task_queue SET status = 'cancelled', finished_at = ? WHERE id = ?`)
      .run(now, id);
  }

  // Generic "reactivate a parked row at its original queue position" —
  // used by both the user-Resume path (task-drawer's Resume button, via
  // patchTaskHandler's blocked -> ready branch) and the HITL-answer path
  // (parkQueueEntryForHitl() above's counterpart), which is exactly why
  // this stays generic rather than baking in either caller's own
  // tasks.status transition. Deliberately leaves pause_reason/paused_at in
  // place (not cleared) so task-execution.ts can still see pausedAt on the
  // next dequeue and send a continuation-flavored kickoff message instead
  // of a fresh-start one — harmless for the HITL case, whose input is
  // driven by task.resumeAnswer instead once that's set.
  resumePausedEntry(id: string): void {
    this.db.prepare(`UPDATE task_queue SET status = 'pending' WHERE id = ?`).run(id);
  }

  // scope is COALESCE(workspace_id, 'inbox') — see dequeueNext()'s comment.
  // origin='agent' rows are excluded, same as dequeueNext()'s runningScopes
  // query — they never occupy a scope's one-running-task slot.
  getRunningEntry(scope: string): (TaskQueueEntry & { task: Task }) | null {
    const row = this.db
      .prepare(
        `SELECT task_queue.*
         FROM task_queue
         JOIN tasks ON tasks.id = task_queue.task_id
         WHERE task_queue.status = 'running' AND tasks.origin != 'agent'
           AND COALESCE(tasks.workspace_id, 'inbox') = ?
         LIMIT 1`,
      )
      .get(scope) as RawQueueRow | undefined;
    if (!row) return null;
    const task = this.getTask(row.task_id);
    if (!task) return null;
    return { ...mapQueueEntry(row), task };
  }

  // All currently-running entries across every scope — used to report
  // "what's running" to the API/SSE layer now that more than one task can be
  // running at once (one per scope), unlike the single-slot getRunningEntry.
  getRunningEntries(): (TaskQueueEntry & { task: Task })[] {
    const rows = this.db
      .prepare(`SELECT * FROM task_queue WHERE status = 'running' ORDER BY position ASC`)
      .all() as RawQueueRow[];
    return rows.flatMap((row) => {
      const task = this.getTask(row.task_id);
      return task ? [{ ...mapQueueEntry(row), task }] : [];
    });
  }
}

// ---------------------------------------------------------------------------
// Boot wiring
// ---------------------------------------------------------------------------

let _store: WorkspaceStore | null = null;

export function bootWorkspaceStore(db: SqliteDatabase): void {
  _store = new WorkspaceStore(db);
  logger.info('Workspace store opened');
}

export function getWorkspaceStore(): WorkspaceStore {
  if (!_store) throw new Error('Workspace store not initialised — call bootWorkspaceStore() first');
  return _store;
}
